PACKET_TYPE_COMMAND  = 0
PACKET_TYPE_RESPONSE = 1
PACKET_TYPE_MESSAGE  = 2

COMMAND_ESTOP  = 0

COMMAND_COLOR_SENSOR = 1
COMMAND_FORWARD = 2
COMMAND_BACKWARD = 3
COMMAND_LEFT = 4
COMMAND_RIGHT = 5
COMMAND_SET_SPEED = 6
COMMAND_STOP = 7

# Robot arm commands
COMMAND_ARM_BASE = 20
COMMAND_ARM_SHOULDER = 21
COMMAND_ARM_ELBOW = 22
COMMAND_ARM_GRIPPER = 23
COMMAND_ARM_HOME = 24
COMMAND_ARM_SET_SPEED = 25

RESP_OK     = 0
RESP_STATUS = 1

RESP_COLOR_SENSOR = 2
RESP_MOTOR_STATUS = 3
RESP_ARM_STATUS = 4

STATE_RUNNING = 0
STATE_STOPPED = 1

MAX_STR_LEN  = 32
PARAMS_COUNT = 16

TPACKET_SIZE = 1 + 1 + 2 + MAX_STR_LEN + (PARAMS_COUNT * 4)  # = 100
TPACKET_FMT  = f'<BB2x{MAX_STR_LEN}s{PARAMS_COUNT}I'

motor_speed = 150

MAGIC = b'\xDE\xAD'          # 2-byte magic number (0xDEAD)
FRAME_SIZE = len(MAGIC) + TPACKET_SIZE + 1   # 2 + 100 + 1 = 103

# Robot arm safety/range constants
ARM_BASE_MIN = 0
ARM_BASE_MAX = 180
ARM_SHOULDER_MIN = 70
ARM_SHOULDER_MAX = 120
ARM_ELBOW_MIN = 60
ARM_ELBOW_MAX = 120
ARM_GRIPPER_MIN = 70
ARM_GRIPPER_MAX = 100
ARM_SPEED_MIN = 1
ARM_SPEED_MAX = 50
